#this runs when the project opens to set up the file structure and 
#last analysis date (aka last time a swift file was opened and quality checked)

source("setup/data_analysis_latest_date.R")
source("config/set_dir_structure.R")
source("config/new_colnames.R")

library(crayon)
library(beepr)
library(odbc)
library(rstudioapi)
library(dbplyr)
library(plyr)
library(dplyr)
library(purrr)
library(tidyr)
library(lubridate)
library(arrow)
library(forcats)
library(ggplot2)
library(plotly)
library(conflicted)
library(phsmethods)
library(stringr)
library(readr)
library(rio)
library(magrittr)
library(janitor)
library(phsstyles)
library(htmlwidgets)
library(parallelly)

conflict_prefer('filter','dplyr')
conflict_prefer('mutate','dplyr')
conflict_prefer('summarise', 'dplyr')
conflict_prefer('rename','dplyr')
conflicts_prefer('count', 'dplyr')
conflict_prefer('arrange','dplyr')

conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::case_when)
conflicts_prefer(dplyr::order_by)
conflicts_prefer(dplyr::lag)
conflicts_prefer(dplyr::lead)
conflicts_prefer(dplyr::first)
