---
output: 
  word_document:
    reference_docx: "phs-offdev-summary.docx"
    fig_caption: no
---


```{r setup, include = FALSE}

library(ggplot2)

```

<Div custom-style = "Publication Title">Child, Adolescent, and Psychological Therapies National Dataset (CAPTND):</Div>
<Div custom-style = "Publication subtitle">`r paste0(dataset_label, " Bi-annual Report")`</Div>
<Div custom-style = "Stats designation">An Official statistics in development release for Scotland</Div>
<Div custom-style = "Publication date">Publication date: `r pub_date`</Div>
<Div custom-style = "Restricted Stats">RESTRICTED STATISTICS: embargoed to 09:30 `r pub_date_dmy`</Div>

# About this release
This release by Public Health Scotland (PHS) provides
an update on information relating to activity in `r dataset_label` (`r dataset_choice`)
`r ifelse(dataset_choice == "PT", "services", "")` from the Child, Adolescent,
and Psychological Therapies National Dataset (CAPTND) in NHS Scotland, for the
period between `r date_label_5qt` and `r date_label`.

`r if(dataset_choice == "CAMHS"){

"CAPTND is a dataset in development that collates information for mental health
services at patient-level and records each individual’s journey through the service 
from referral to discharge. CAPTND data are still under development therefore any 
inferences or conclusions from this analysis must be treated with caution, and should
not be compared to the [official aggregate CAMHS collection and waiting times](https://publichealthscotland.scot/publications/child-and-adolescent-mental-health-services-camhs-waiting-times/child-and-adolescent-mental-health-services-camhs-waiting-times-quarter-ending-september-2026/)

Improving data quality in CAPTND is an ongoing process, meaning data from previous 
quarters may not be directly comparable to the current reporting period. Changes in 
data over the past five quarters could be reflective of improved data quality of 
submissions, rather than necessarily representing an actual increase in service demand.       
    
CAMHS are multi-disciplinary teams that provide treatment and/or interventions for 
children and young people experiencing mental health problems. Note that where a 
child or young person is waiting for an assessment for a neurodevelopmental (ND) 
condition such as autistic spectrum disorder (ASD), or attention deficit hyperactivity 
disorder (ADHD), they may not meet the national referral criteria as set out in the 
[CAMHS national service specification](https://www.gov.scot/publications/child-adolescent-mental-health-services-camhs-nhs-scotland-national-service-specification/pages/1/) and therefore will not be counted in these 
statistics. PHS is commissioned to collect information on CAMHS, excluding ND 
pathway activity.       
    
This release does not report on the neurodevelopmental (ND) pathway including those
children and young people on the neurodevelopmental waiting list. Please see the ND
activity section of the [data quality document](https://publichealthscotland.scot/publications/child-adolescent-and-psychological-therapies-national-dataset-captnd/child-and-adolescent-mental-health-services-in-child-adolescent-and-psychological-therapies-national-dataset-3-march-2026/), and the [national neurodevelopmental specification: principles and standards of care](https://www.gov.scot/publications/national-neurodevelopmental-specification-children-young-people-principles-standards-care/) for more information."        

}else{

"CAPTND is a dataset in development that collates information for mental health
services at patient-level and records each individual’s journey through the service 
from referral to discharge. CAPTND data are still under development therefore any 
inferences or conclusions from this analysis must be treated with caution, and should
not be compared to the [official aggregate PT collection and waiting times](https://publichealthscotland.scot/publications/psychological-therapies-waiting-times/psychological-therapies-waiting-times-quarter-ending-september-2026/).

Improving data quality in CAPTND is an ongoing process, meaning data from previous 
quarters may not be directly comparable to the current reporting period. Changes 
in data over the past five quarters could be reflective of improved data quality 
of submissions, rather than necessarily representing an actual increase in service demand. 
For more information regarding the data quality of this release, please see the 
accompanying [data quality document](https://publichealthscotland.scot/publications/child-adolescent-and-psychological-therapies-national-dataset-captnd/child-and-adolescent-mental-health-services-in-child-adolescent-and-psychological-therapies-national-dataset-3-march-2026/)"
}`

# Main Points
For `r dataset_choice` data recorded in CAPTND across NHS Scotland,  in the quarter ending `r date_label`:  

<Div custom-style = "Bullet 1"> 
`r figs_referrals$current_qt`
`r ifelse(dataset_choice == "CAMHS", "children and young people", "people of all ages")` 
were referred. This was `r ifelse(figs_referrals$diff_qt > 0, "an increase", "a decrease")` of 
`r gsub("-", "", figs_referrals$diff_qt)` (`r gsub("-", "", figs_referrals$prop_qt)`%) compared with the
`r figs_referrals$last_qt` referrals in the previous quarter, and
`r ifelse(figs_referrals$diff_yr > 0, "an increase", "a decrease")` of `r gsub("-", "", figs_referrals$diff_yr)` 
(`r gsub("-", "", figs_referrals$prop_yr)`%) compared with the `r figs_referrals$last_yr` referrals
in the same quarter ending `r date_label_yr`.
</Div>

<Div custom-style = "Bullet 1"> 
Of the `r figs_referrals$current_qt` referrals received, `r agesex_total_last_qt[[1,4]]`% 
were for females and `r agesex_total_last_qt[[2,4]]`% for males. These proportions have 
remained fairly static in the 15 months of reporting shown in this publication.
</Div>

<Div custom-style = "Bullet 1">
The referral acceptance rate was `r figs_ref_acc[[1,5]]`%; lower than the acceptance rate
of `r figs_ref_acc[[1,4]]`% in the previous quarter, and `r figs_ref_acc[[1,3]]`% accepted 
in the same quarter ending `r date_label_yr`.
</Div>

<Div custom-style = "Bullet 1">
`r table_data3[[15,2]]` `r dataset_choice` appointments were allocated and recorded 
in CAPTND across. This is `r ifelse(figs_apps_qt$diff_qt > 0, "an increase", "a decrease")`
of `r gsub("-", "", figs_apps_qt$prop_qt)`% of total recorded appointments since the
previous quarter, and `r ifelse(figs_apps_qt$diff_yr > 0, "an increase", "a decrease")` 
of `r gsub("-", "", figs_apps_qt$prop_yr)`% recorded appointments since the same quarter
ending `r date_label_yr`.  Note this may be reflective of improved data quality of submissions,
rather than an actual increase in service demand. 
</Div>

<Div custom-style = "Bullet 1">
Of the `r table_data3[[15,2]]` appointments recorded, `r figs_tot_apps[[1,2]]` 
had an attendance status of 'Did Not Attend (DNA)' resulting in a total DNA rate 
of `r figs_tot_apps[[1,3]] ` for all appointments.
</Div>


# Background

`r if(dataset_choice == "CAMHS"){

"PHS is continuing to develop CAPTND and accompanying narratives. There are plans 
underway to review reporting methods and include additional measures such as waiting 
times from CAPTND when the data quality of further measures is deemed sufficient. 
NHS health boards are working with PHS and the Scottish Government to improve the 
consistency and completeness of the information."  

}else{

"PHS is continuing to develop CAPTND and accompanying narratives. There are plans 
underway to review reporting methods and include additional measures such as waiting 
times from CAPTND when the data quality of further measures is deemed sufficient. 
NHS health boards are working with PHS and the Scottish Government to improve the 
consistency and completeness of the information.               
    
Psychological therapies refer to a range of interventions, based on psychological 
concepts and theory, which are designed to help people understand and make changes 
to their thinking, behaviour and relationships in order to relieve distress and to 
improve functioning. The standard applies specifically to psychological therapies 
for treatment of a mental illness or disorder."    

}`

# Contact
Alan Coventry | Senior Information Analyst | [phs.captnd@phs.scot](mailto:phs.captnd@phs.scot)

Luke Taylor | Senior Information Analyst | [phs.captnd@phs.scot](mailto:phs.captnd@phs.scot)

For all media enquiries please email [phs.comms@phs.scot](mailto:phs.comms@phs.scot) or call 0131 275 6105.

# Further information
Data from this publication are available from the [publication page]`r paste0("(https://publichealthscotland.scot/publications/child-adolescent-and-psychological-therapies-national-dataset-captnd/", dataset_choice, "-in-captnd-2-september-2025/)")` on our website.

Our statistical practice is regulated by the Office for Statistics Regulation (OSR). Official Statistics in development are official statistics which are undergoing a development. 

Visit our website for [further information about our statistics and PHS as an Official Statistics producer.](https://publichealthscotland.scot/our-organisation/about-our-statistics/official-statistics/)

The next release of this publication will be `r next_pub_date`.

Other formats of this publication are available on request by calling 0131 314 5300 or emailing [phs.otherformats@phs.scot](mailto:phs.otherformats@phs.scot).

