---
output: 
  word_document:
    reference_docx: "phs-offdev-summary.docx"
    fig_caption: no
---


```{r setup, include = FALSE}

library(ggplot2)

```

<Div custom-style = "Publication Title">Child, Adolescent, and Psychological Therapies National Dataset (CAPTND):</Div>
<Div custom-style = "Publication subtitle">`r paste0(dataset_label, " Report")`</Div>
<Div custom-style = "Stats designation">An Official statistics in development release for Scotland</Div>
<Div custom-style = "Publication date">Publication date: 03 September 2024</Div>
<Div custom-style = "Restricted Stats">RESTRICTED STATISTICS: embargoed to 09:30 03/09/2024</Div>

# About this release
This statistics in development release by Public Health Scotland (PHS) provides
an update on information relating to activity in `r dataset_label` (`r dataset_choice`)
`r ifelse(dataset_choice == "PT", "services", "")` from the Child, Adolescent,
and Psychological Therapies National Dataset (CAPTND) in NHSScotland, for the
quarter ending `r date_label`.

# Main Points
CAPTND is a dataset in development that collates information for mental health
services at patient-level and records each individual’s journey through the service.
CAPTND data are still under development therefore any inferences or conclusions
from this analysis must be treated with caution.  

For `r dataset_choice` in the quarter ending `r date_label`:  

<Div custom-style = "Bullet 1"> 
There were a total of `r figs_referrals$current_qt`
`r ifelse(dataset_choice == "CAMHS", "children and young people", "people")` 
referred to `r dataset_choice` and recorded in CAPTND.
This was `r ifelse(figs_referrals$diff_qt > 0, "an increase", "a decrease")` of 
`r gsub("-", "", figs_referrals$diff_qt)` (`r gsub("-", "", figs_referrals$prop_qt)`%) compared with the
`r figs_referrals$last_qt` referrals in the previous quarter, and
`r ifelse(figs_referrals$diff_yr > 0, "an increase", "a decrease")` of `r gsub("-", "", figs_referrals$diff_yr)` 
(`r gsub("-", "", figs_referrals$prop_yr)`%) compared with the `r figs_referrals$last_yr` referrals
in the same quarter ending `r date_label_yr`.
</Div>

<Div custom-style = "Bullet 1">
Of the `r table_data2[[15,2]]` referrals to `r dataset_choice`, `r table_data2[[15,3]]`
(`r table_data2[[15,6]]`) were accepted. Of the `r table_data2[[15,4]]` referrals
not accepted, `r ref_rej_reasons[[1,5]]` (`r ref_rej_reasons[[1,7]]`%) were due
to the individual referred being unsuitable for treatment in `r dataset_choice`
`r ifelse(dataset_choice == "PT", " services", "")`.
</Div>

<Div custom-style = "Bullet 1">
There were a total of `r table_data3[[15,2]]` `r dataset_choice` appointments recorded in CAPTND 
across NHS Scotland. This is `r ifelse(figs_apps_qt$diff_qt > 0, "an increase", "a decrease")`
of `r gsub("-", "", figs_apps_qt$diff_qt)` (`r gsub("-", "", figs_apps_qt$prop_qt)`%)
recorded appointments since the previous quarter, and
`r ifelse(figs_apps_qt$diff_yr > 0, "an increase", "a decrease")` of
`r gsub("-", "", figs_apps_qt$diff_yr)` (`r gsub("-", "", figs_apps_qt$prop_yr)`%)
recorded appointments since the same quarter in the previous year.
</Div>


# Background

Waiting times information for Child and Adolescent Mental Health Services (CAMHS) and 
psychological therapies using CAPTND is still being developed. NHS health boards
are working with PHS and the Scottish Government to improve the consistency and
completeness of the 
information.  

`r if(dataset_choice == "CAMHS"){

"CAMHS are multi-disciplinary teams that provide treatment and/or interventions for children and
young people experiencing mental health problems. Where a child or young person is waiting
for an assessment for a neurodevelopmental condition such as ASD, or ADHD, they may not be
appropriate for CAMHS. This release does not report on the neurodevelopmental (ND) pathway
including those children and young people on the neurodevelopmental waiting list."

}else{

"Psychological therapies refer to a range of interventions, based on psychological concepts and
theory, which are designed to help people understand and make changes to their thinking,
behaviour and relationships in order to relieve distress and to improve functioning. The standard
applies specifically to psychological therapies for treatment of a mental illness or disorder."
}`

# Contact
Charlie Smith | Senior Information Analyst | [phs.captnd@phs.scot](mailto:phs.captnd@phs.scot)

Bex Madden | Information Analyst | [phs.captnd@phs.scot](mailto:phs.captnd@phs.scot)

For all media enquiries please email [phs.comms@phs.scot](mailto:phs.comms@phs.scot) or call 0131 275 6105.

# Further information
Data from this publication are available from the [publication page](https://publichealthscotland.scot/publications/child-adolescent-and-psychological-therapies-national-dataset-captnd/) on our website.

Open data from this publication is available from the [Scottish Health and Social Care Open Data platform](https://www.opendata.nhs.scot/).

Our statistical practice is regulated by the Office for Statistics Regulation (OSR). Official Statistics in development are official statistics which are undergoing a development. 

Visit our website for [further information about our statistics and PHS as an Official Statistics producer.](https://publichealthscotland.scot/our-organisation/about-our-statistics/official-statistics/)

The next release of this publication will be `r next_pub_date`.

Other formats of this publication are available on request by calling 0131 314 5300 or emailing [phs.otherformats@phs.scot](mailto:phs.otherformats@phs.scot).

# NHS Performs
A selection of information from this publication is included in [NHS Performs](http://www.nhsperforms.scot). NHS Performs is a website that brings together a range of information on how hospitals and NHS Boards within NHSScotland are performing.
